==== Rooms
Logical event group of the chat room domain. All reactive operations from the bounded context of the chat
rooms are listed below.

===== Event: join
Event can be emitted by the client to join a chat room. All available rooms that can be accessed via the
RESTful interface are eligible. See <<_rooms, Rooms>> for details.

[horizontal]
Name:: `twaddle/room:join`
Emitter:: Client

.Payload Fields
[cols="1,1,1,1] 
|===
|Field |Type |Description |Required

|id
|String
|Identifier of room to join.
|true
|===

===== Event: joined
Event is sent from the server to the client as a result of a successful room join. It confirms successful entry.

[horizontal]
Name:: `twaddle/room:joined`
Emitter:: Server

===== Event: leave
Allows a client to leave a chat room by sending this event.

[horizontal]
Name:: `twaddle/room:leave`
Emitter:: Client

===== Event: left
Event is used to confirm a client leaving the chat room.

[horizontal]
Name:: `twaddle/room:left`
Emitter:: Server

===== Event: user-list
This event is sent by the server to inform the clients about the current list of joined users.

[horizontal]
Name:: `twaddle/room:user-list`
Emitter:: Server

.Payload Fields
[cols="1,1,1,1] 
|===
|Field |Type |Description |Required

|users
|Array
|Array of usernames of current room's users.
|true
|===

===== Event: user-joined
Notifies the remaining users of a chat room that a new user has joined.

[horizontal]
Name:: `twaddle/room:user-joined`
Emitter:: Server

.Payload Fields
[cols="1,1,1,1] 
|===
|Field |Type |Description |Required

|user
|String
|Username of user that joined.
|true
|===

===== Event: user-left
Informs the remaining users of a chat room about leaving another user's room.

[horizontal]
Name:: `twaddle/room:user-left`
Emitter:: Server

.Payload Fields
[cols="1,1,1,1] 
|===
|Field |Type |Description |Required

|user
|String
|Username of user that left.
|true
|===

===== Event: send
Sent by the client to send a new message to the chat. This event stops the server from redistributing the message.

[horizontal]
Name:: `twaddle/room:send`
Emitter:: Client

.Payload Fields
[cols="1,1,1,1] 
|===
|Field |Type |Description |Required

|message
|String
|Message to send.
|true
|===

===== Event: message
Used by the server to broadcast received messages.

[horizontal]
Name:: `twaddle/room:message`
Emitter:: Server

.Payload Fields
[cols="1,1,1,1] 
|===
|Field |Type |Description |Required

|id
|String
|Unique identifier of message.
|true

|content
|String
|The actual message sent in chat.
|true

|room
|String
|Identifier of the room in which the message was sent.
|true

|username
|String
|Unique username of user that sent the message.
|true

|timestamp
|String
|Time of sending the message.
|true
|===
