==== Rooms
Logical event group of the chat room domain. All reactive operations from the bounded context of the chat
rooms are listed below.

===== Event: join
Event can be emitted by the client to join a chat room. All available rooms that can be accessed via the
RESTful interface are eligible. See <<_rooms, Rooms>> for details.

[horizontal]
Name:: `twaddle/room:join`
Emitter:: Client

.Payload Fields
[cols="1,1,1,1] 
|===
|Field |Type |Description |Required

|id
|String
|Identifier of room to join.
|true
|===

===== Event: joined
Event is sent from the server to the client as a result of a successful room join. It confirms successful entry.

[horizontal]
Name:: `twaddle/room:joined`
Emitter:: Server

===== Event: leave
Allows a client to leave a chat room by sending this event.

[horizontal]
Name:: `twaddle/room:leave`
Emitter:: Client

===== Event: left
Event is used to confirm a client leaving the chat room.

[horizontal]
Name:: `twaddle/room:left`
Emitter:: Server

===== Event: user-list
This event is sent by the server to inform the clients about the current list of joined users.

[horizontal]
Name:: `twaddle/room:user-list`
Emitter:: Server

.Payload Fields
[cols="1,1,1,1] 
|===
|Field |Type |Description |Required

|users
|Array
|Array of usernames of current room's users.
|true
|===

===== Event: user-joined
Notifies the remaining users of a chat room that a new user has joined.

[horizontal]
Name:: `twaddle/room:user-joined`
Emitter:: Server

.Payload Fields
[cols="1,1,1,1] 
|===
|Field |Type |Description |Required

|user
|String
|Username of user that joined.
|true
|===

===== Event: user-left
Informs the remaining users of a chat room about leaving another user's room.

[horizontal]
Name:: `twaddle/room:user-left`
Emitter:: Server

.Payload Fields
[cols="1,1,1,1] 
|===
|Field |Type |Description |Required

|user
|String
|Username of user that left.
|true
|===

===== Event: send
This event is triggered by the client to send a new message to all chat participants. The message to
be sent can be a pure text message (`TEXT`) or a multimedia message (`IMAGE`, `VIDEO` or `AUDIO`).

It should be noted that in the case of multimedia messages, it is not the actual content that is
transmitted via the _Twaddle Communication API_. Instead, the medium must first be uploaded as an
attachment via the <<_attachments, Twaddle Management API>>. Instead, the unique identifier of the
attachment is transferred.

[horizontal]
Name:: `twaddle/room:send`
Emitter:: Client

.Payload Fields
[cols="1,1,1,1] 
|===
|Field |Type |Description |Required

|content
|String
|The actual content of the message. This field is not required for multimedia messages.
|false

|attachment
|String
|Contains the unique identifier of the previously uploaded multimedia attachment. This field is only required if
a multimedia message is to be sent.
|false

|type
|String
|Type of message. Basically there are 4 types of messages: Simple `TEXT` messages, `IMAGE`, `VIDEO` or `AUDIO` messages.
|true
|===

===== Event: message
Used by the server to broadcast received messages.

[horizontal]
Name:: `twaddle/room:message`
Emitter:: Server

.Payload Fields
[cols="1,1,1,1] 
|===
|Field |Type |Description |Required

|id
|String
|Unique identifier of message.
|true

|type
|String
|Type of message. Basically there are 4 types of messages: Simple 'TEXT' messages, 'IMAGE', 'VIDEO' or 'AUDIO' messages.
|true

|content
|String
|The actual message content. This field does not exist for multimedia messages.
|false

|attachment
|String
|Contains the unique identifier of the multimedia attachment. This field only exists for multimedia messages.
The actual media can be downloaded via <<_attachments, Attachments>>.
|false

|room
|String
|Identifier of the room in which the message was sent.
|true

|user
|String
|Username of the user who sent the message.
|true

|timestamp
|String
|Time of sending the message.
|true
|===
