= Twaddle API
:favicon: /favicon.svg
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:

== Introduction
This is the official documentation of the Twaddle Platform API. Twaddle is a messenger with user management
for mutual communication exchange in real time. This API enables programmatic access to the Twaddle Platform,
all data and connections come together here.

From a technical point of view, the API can be divided into two further APIs. Into an HTTP based RESTful
interface and a reactive web socket interface. The RESTful interface is used to retrieve general information,
while real-time communication is implemented via the web socket interface.

== RESTful API
This API is essentially used for static information management. Account management and authentication are
essentially handled through this part of the Twaddle API. It is essentially a supporting interface with no
direct part in the core domain.

Technically, the interface is based on the https://datatracker.ietf.org/doc/html/rfc2616/[HTTP] protocol and
follows the RESTful specification. The interface is therefore organized in resources.

=== Fundamentals

==== Versioning
For reasons of backward compatibility, multiple versions of the API are enabled in parallel. Depending on the
version, paths, resources and endpoints may differ. Versioning for the Twaddle API will be represented by
version numbers declared in the route path for our endpoints:

[source,http,options="nowrap"]
----
http://<DOMAIN>/api/v1
----

Versioning is intended to prevent developers from being confronted with breaking changes overnight. Therefore,
if available, several major releases are operated in parallel. At the moment the following major versions are
available:

* Version 1: `http://<DOMAIN>/api/v1`

NOTE: It is not possible to omit the version. By default, each call must be preceded by the prefix `api` and a version.

==== Content negotiation
This API doesn't support content negotiation. For the sake of simplicity, only
https://datatracker.ietf.org/doc/html/rfc8259[JSON] is consumed and only https://datatracker.ietf.org/doc/html/rfc8259[JSON]
is produced. This applies without exception API wide. The media types `application/json; charset=utf-8` or `application/json`
are to be expected/used.

==== Pagination
Depending on the resources, huge amounts of data can accumulate. In order to prevent network and client overload,
these data volumes are not fully loaded by default. Instead, the data is transmitted paged. Whether pagination is
supported depends on the specific endpoint. However, the Pagination format API is widely uniform. The pagination
behavior can be controlled via the following HTTP query parameters:

.Pagination Query Parameters
[cols="1,1,1] 
|===
|Parameter |Description |Optional

|page
|Specifies the page to load. It must be a positive integer and the index is zero-based. By default the value is 0.
|true

|perPage
|Indicates the size of a page, i.e. how many elements are to be loaded with a page at once. By default the value is 25.
|true
|===

The response contains the requested page depending on the optional query parameter.

.Pagination Response Fields
[cols="1,1,1,1] 
|===
|Field |Type |Description |Optional

|info
|Object
|Contains meta information like size and index of the page.
|false

|info.page
|Number
|Zero based integer that specifies the page index.
|false

|info.perPage
|Number
|Integer that gives the page size.
|false

|info.totalElements
|Number
|Integer that gives the amount of total elements in data source.
|false

|info.totalPages
|Number
|Integer that gives the amount of available pages.
|false

|content
|Array
|Contains an array of actual data.
|false
|===

==== Error handling
The interface uses a uniform error format which, in addition to the HTTP status codes, also uses internal error codes.

.Error Response Fields
[cols="1,1,1,1] 
|===
|Field |Type |Description |Optional

|status
|Number
|HTTP status code used in response.
|false

|code
|String
|API internal error code. See <<_error_codes, Error codes>> for details.
|false

|message
|String
|Humans Legible message describing the error. The message is not i18n compliant.
|false

|details
|Array
|Additional information for describing the error more detailed.
|true
|===

===== Error codes
The following error codes are used by the API and are intended to allow the client to respond more specifically to errors.

.Error Codes
[cols="1,1] 
|===
|Code |Description

|InternalServerError
|Basic code which indicates an unexpected error. This can only be fixed on the server side.

|NotFoundError
|Used when a resource could not be found. Check for wrong paths or missing path variables.

|InvalidQueryParameterError
|Used when a wrong HTTP query parameter is used or the validation of it failed.

|InvalidPathVariableError
|Used when a path variable is missing or malformed.

|ValidationError
|Used when the requets body validation failed due to semantic errors.

|InvalidCredentialsError
|Used when the user credentials, username and password, are wrong.

|InvalidTokenError
|Used when the access token is invalid.

|AccessDeniedError
|Used when permission is denied.

|RoomNameAlreadyInUseError
|It is not possible to name the room because a room with this name already exists.

|UsernameAlreadyInUseError
|The username is already in use.

|EmailAlreadyInUseError
|The email address is already in use.

|MustBeAdministrableError
|The operation, usually changing a user, is not possible to ensure manageability.
|===

==== Authentication
Most endpoints require identification of the client. Different techniques are used depending on the end point. In principle,
however, authentication takes place via a stateless `Bearer` access token.

An access token can be issued for a user account for the duration of its validity. There is a RESTful endpoint for this,
which accepts the credentials and, if necessary, issues an access token. For details see
<<_tokens, Tokens>>. The token must then be given with every request in the `Authorization`
HTTP header.

[source,http,options="nowrap"]
----
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU5JU1RSQVRPUiIsImlhdCI6MTY0NTQ1MTgyNiwiZXhwIjoxNjQ1NDUyMTI2LCJpc3MiOiJUd2FkZGxlIEFQSSIsInN1YiI6Im1heGkifQ.QA7fQXvf0f21JUtdxgLrJO6BdqxyrY66kRrWiHqYwrjEjvA46NT74IYhGf3uSS1_dMT131mZe_chc8qhXnjUXS1xbEntI7jwlPxPl9x0kiF6FSrkCtyazqwvHUnwpokNUH3xmfVvUYjCM2GH0wEkXndovebykK_1hFLpXrUQSPU
----

=== Resources

include::restful/tokens.adoc[]

include::restful/tickets.adoc[]

include::restful/users.adoc[]

include::restful/profiles.adoc[]

include::restful/rooms.adoc[]

== Web Socket API
This interface enables operations in the core domain, which essentially include real-time message exchange.

Technically, the interface is based on the https://datatracker.ietf.org/doc/html/rfc6455[WebSocket] protocol and
follows a custom message specification. The interface is event-based. This API uses the
https://github.com/socketio/socket.io-protocol[Socket.IO] protocol as communication layer.

NOTE: Only one web socket connection per user is allowed. Attempting to create more than one will result in an error.

CAUTION: Authentication is always required to open a web socket connection. See <<_authentication_2, Authentication>> for details.

=== Fundamentals

==== Versioning
Just like the RESTful interface, for the sake of the of backward compatibility, multiple versions of the API are enabled in parallel.
Depending on the version, events, resources and endpoints may differ. Versioning for the Twaddle API will be represented by
version numbers declared in the route path for our endpoints:

[source,http,options="nowrap"]
----
ws://<DOMAIN>/ws/v1
----

Versioning is intended to prevent developers from being confronted with breaking changes overnight. Therefore,
if available, several major releases are operated in parallel. At the moment the following major versions are
available:

* Version 1: `http://<DOMAIN>/ws/v1`

NOTE: It is not possible to omit the version. By default, each call must be preceded by the prefix `ws` and a version.

==== Authentication
Basically, a web socket connection cannot be established without authentication. For reasons of compatibility, authentication is not carried out via token as with
the RESTful API, but via ticket.

An ticket can be issued, just like a token, for a user account for the duration of its validity. There is also a RESTful endpoint for this,
which accepts an access token and, if necessary, issues an access token. For details see <<_tickets, Tickets>>. The ticket must then be given with every request
as `ticket` query parameter.

[source,http,options="nowrap"]
----
ws://<DOMAIN>/ws/v1?ticket=eb12a561895153c3f0b70325
----

==== Content negotiation
This API doesn't support content negotiation. The https://github.com/socketio/socket.io-protocol[Socket.IO] protocol is
used as the message format, which in turn is based on JSON. The payload used by the API and sent on the basis of
https://github.com/socketio/socket.io-protocol[Socket.IO] is also JSON formatted data.

==== Events
If the terminology "event" is used in the following, it is always an event in the sense of the
https://github.com/socketio/socket.io-protocol[Socket.IO] specification and not in the sense of the technical
https://datatracker.ietf.org/doc/html/rfc6455[WebSocket] specification.

Basically, a distinction must be made between low-level events, i.e. events of the underlying web socket implementation,
and business events, i.e. events of the Twaddle Platform. Business events always begin with the prefix `twaddle/`.
Alternatively, a namespace can follow, e.g. `twaddle/room:join`, or the event applies to the global namespace,
e.g. `twaddle/error`.

==== Error handling
Just like the RESTful interface, there is a consistent error format.

In case of an error, the event `twaddle/error` is used all the time. Sometimes errors occur even before a technical web socket connection has been established, for example in the case of insufficient authentication. In this case, the connection
is not established at all and the low-level event `connect_error` is used.

.Error Response Fields
[cols="1,1,1,1] 
|===
|Field |Type |Description |Optional

|code
|String
|API internal error code. See <<_error_codes_2, Error codes>> for details.
|false

|message
|String
|Humans Legible message describing the error. The message is not i18n compliant.
|false

|details
|Array
|Additional information for describing the error more detailed.
|true
|===

===== Error codes
The following error codes are used by the Web Socket API and are intended to allow the client to respond more specifically to errors.

.Error Codes
[cols="1,1] 
|===
|Code |Description

|InternalServerError
|Basic code which indicates an unexpected error. This can only be fixed on the server side.

|NotFoundError
|Used when a resource can't be found.

|InvalidTicketError
|Used when the authentication ticket is invalid.

|AlreadyConnectedError
|Used when a user tries to establish a second web socket connection. Only one connection is allowed per user.
|===

=== Resources

include::socket/rooms.adoc[]
