==== Rooms
Represents the chat rooms in which you can write.

===== Create room
Creates a new chat room.

[horizontal]
Method:: POST
Path:: /api/v1/rooms
Authentication:: Yes

====== Request

.Request Fields
[cols="1,1,1] 
|===
|Field |Type |Description |Required

|name
|String
|Name of the new room.
|true

|description
|String
|Description of the new room.
|true
|===

.Request Example
[%collapsible]
====
[source,http,options="nowrap"]
----
POST /api/v1/rooms HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU5JU1RSQVRPUiIsImlhdCI6MTY0NTExMzQ4NiwiZXhwIjoxNjQ1MTEzNzg2LCJpc3MiOiJUd2FkZGxlIEFQSSIsInN1YiI6Im1heGkifQ.YuwEfMI8h9VHj3kou5pfVDe6tvQHKpNdNUoe0mFpCLxRTufpWxtOg0gd_chXq8ffXVov0qxyZ1ig_HwdbwGUFHZWtdL2PNUkqNkPbAfHB_N_gLmBGXBACgn1DPaFItaNKi0gE3loCgHmGemL4ONEk-si02GrsfqJQL96bwGAaB8
Accept: application/json
Content-Length: 73

{
  "name": "Lobby",
  "description": "Main room to talk about anything."
}
----
====

====== Response

.Response Fields
[cols="1,1,1,1] 
|===
|Field |Type |Description |Required

|id
|String
|Unique hexadecimal identifier of the room.
|true

|name
|String
|Room's name.
|true

|description
|String
|Room's description.
|true

|createdAt
|String
|Timestamp of the creation.
|true
|===

.Response Example
[%collapsible]
====
[source,http,options="nowrap"]
----
HTTP/1.1 201 Created
Content-Type: application/json; charset=utf-8
Content-Length: 137

{
	"id": "620e70984248fc97396eb976",
	"name": "Lobby",
	"description": "Main room to talk about anything.",
	"createdAt": "2022-02-17T15:58:16.598Z"
}
----
====

===== Get rooms
Get all available rooms paged. See <<_pagination, Pagination>> for details.

[horizontal]
Method:: GET
Path:: /api/v1/rooms
Authentication:: Yes
Pagination:: Yes
Filtering:: Yes

====== Request

.Request Example
[%collapsible]
====
[source,http,options="nowrap"]
----
GET /api/v1/rooms HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU5JU1RSQVRPUiIsImlhdCI6MTY0NTExMzQ4NiwiZXhwIjoxNjQ1MTEzNzg2LCJpc3MiOiJUd2FkZGxlIEFQSSIsInN1YiI6Im1heGkifQ.YuwEfMI8h9VHj3kou5pfVDe6tvQHKpNdNUoe0mFpCLxRTufpWxtOg0gd_chXq8ffXVov0qxyZ1ig_HwdbwGUFHZWtdL2PNUkqNkPbAfHB_N_gLmBGXBACgn1DPaFItaNKi0gE3loCgHmGemL4ONEk-si02GrsfqJQL96bwGAaB8
Accept: application/json
----
====

====== Response

.Response Fields
[cols="1,1,1,1] 
|===
|Field |Type |Description |Required

|content
|Array
|Array of found resources.
|true

|content[].id
|String
|Unique hexadecimal identifier of the room.
|true

|content[].name
|String
|Room's name.
|true

|content[].description
|String
|Room's description.
|true

|content[].createdAt
|String
|Timestamp of the creation.
|true
|===

.Response Example
[%collapsible]
====
[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Content-Length: 215

{
	"content": [
		{
			"id": "620e70984248fc97396eb976",
			"name": "Lobby",
			"description": "Main room to talk about anything.",
			"createdAt": "2022-02-17T15:58:16.598Z"
		}
	],
	"info": {
		"page": 0,
		"perPage": 25,
		"totalPages": 1,
		"totalElements": 1
	}
}
----
====

===== Get room
Get a room by its identifier.

[horizontal]
Method:: GET
Path:: /api/v1/rooms/:id
Authentication:: Yes

====== Request

.Path Variables
[cols="1,1,1] 
|===
|Variable |Type |Description |Required

|id
|String
|Unique identifier of room to search for.
|true
|===

.Request Example
[%collapsible]
====
[source,http,options="nowrap"]
----
GET /api/v1/rooms/620e70984248fc97396eb976 HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU5JU1RSQVRPUiIsImlhdCI6MTY0NTExMzQ4NiwiZXhwIjoxNjQ1MTEzNzg2LCJpc3MiOiJUd2FkZGxlIEFQSSIsInN1YiI6Im1heGkifQ.YuwEfMI8h9VHj3kou5pfVDe6tvQHKpNdNUoe0mFpCLxRTufpWxtOg0gd_chXq8ffXVov0qxyZ1ig_HwdbwGUFHZWtdL2PNUkqNkPbAfHB_N_gLmBGXBACgn1DPaFItaNKi0gE3loCgHmGemL4ONEk-si02GrsfqJQL96bwGAaB8
Accept: application/json
----
====

====== Response

.Response Fields
[cols="1,1,1,1] 
|===
|Field |Type |Description |Required

|id
|String
|Unique hexadecimal identifier of the room.
|true

|name
|String
|Room's name.
|true

|description
|String
|Room's description.
|true

|createdAt
|String
|Timestamp of the creation.
|true
|===

.Response Example
[%collapsible]
====
[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Content-Length: 97

{
	"id": "620e70984248fc97396eb976",
	"name": "Lobby",
	"description": "Main room to talk about anything",
  "createdAt": "2022-02-17T15:58:16.598Z"
}
----
====

===== Delete room
Delete a room by its identifier.

[horizontal]
Method:: DELETE
Path:: /api/v1/rooms/:id
Authentication:: Yes

====== Request

.Path Variables
[cols="1,1,1] 
|===
|Variable |Type |Description |Required

|id
|String
|Unique identifier of room to search for.
|true
|===

.Request Example
[%collapsible]
====
[source,http,options="nowrap"]
----
DELETE /api/v1/rooms/620e70984248fc97396eb976 HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU5JU1RSQVRPUiIsImlhdCI6MTY0NTExMzQ4NiwiZXhwIjoxNjQ1MTEzNzg2LCJpc3MiOiJUd2FkZGxlIEFQSSIsInN1YiI6Im1heGkifQ.YuwEfMI8h9VHj3kou5pfVDe6tvQHKpNdNUoe0mFpCLxRTufpWxtOg0gd_chXq8ffXVov0qxyZ1ig_HwdbwGUFHZWtdL2PNUkqNkPbAfHB_N_gLmBGXBACgn1DPaFItaNKi0gE3loCgHmGemL4ONEk-si02GrsfqJQL96bwGAaB8
Accept: application/json
----
====

====== Response

.Response Example
[%collapsible]
====
[source,http,options="nowrap"]
----
HTTP/1.1 204 No Content
Content-Type: application/json; charset=utf-8
----
====

===== Update room
Update a room by its identifier.

[horizontal]
Method:: PATCH
Path:: /api/v1/rooms/:id
Authentication:: Yes

====== Request

.Path Variables
[cols="1,1,1] 
|===
|Variable |Type |Description |Required

|id
|String
|Unique identifier of room to search for.
|true
|===

.Request Fields
[cols="1,1,1] 
|===
|Field |Type |Description |Required

|name
|String
|Name of the new room.
|false

|description
|String
|Description of the new room.
|false
|===

.Request Example
[%collapsible]
====
[source,http,options="nowrap"]
----
PATCH /api/v1/rooms/620e70984248fc97396eb976 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU5JU1RSQVRPUiIsImlhdCI6MTY0NTExMzQ4NiwiZXhwIjoxNjQ1MTEzNzg2LCJpc3MiOiJUd2FkZGxlIEFQSSIsInN1YiI6Im1heGkifQ.YuwEfMI8h9VHj3kou5pfVDe6tvQHKpNdNUoe0mFpCLxRTufpWxtOg0gd_chXq8ffXVov0qxyZ1ig_HwdbwGUFHZWtdL2PNUkqNkPbAfHB_N_gLmBGXBACgn1DPaFItaNKi0gE3loCgHmGemL4ONEk-si02GrsfqJQL96bwGAaB8
Accept: application/json
Content-Length: 18

{
  "name": "Main"
}
----
====

====== Response

.Response Fields
[cols="1,1,1,1] 
|===
|Field |Type |Description |Required

|id
|String
|Unique hexadecimal identifier of the room.
|true

|name
|String
|Room's name.
|true

|description
|String
|Room's description.
|true

|createdAt
|String
|Timestamp of the creation.
|true
|===

.Response Example
[%collapsible]
====
[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Content-Length: 136

{
	"id": "620e70984248fc97396eb976",
	"name": "Main",
	"description": "Main room to talk about anything.",
	"createdAt": "2022-02-17T15:58:16.598Z"
}
----
====
