==== Users
Represents the user accounts with the details.

===== Create user
Creates a new user.

[horizontal]
Method:: POST
Path:: /api/v1/users

NOTE: The first user who registers on the platform is automatically made an administrator.

====== Request

.Request Fields
[cols="1,1,1] 
|===
|Field |Type |Description |Required

|username
|String
|Unique name of user
|true

|email
|String
|Unique email of user.
|true

|password
|String
|Password of the new account
|true
|===

.Request Example
[%collapsible]
====
[source,http,options="nowrap"]
----
POST /api/v1/users HTTP/1.1
Content-Type: application/json
Accept: application/json
Content-Length: 74

{
  "username": "timi",
  "email": "timi@gmail.com",
  "password": "Abc123"
}
----
====

====== Response

.Response Fields
[cols="1,1,1,1] 
|===
|Field |Type |Description |Required

|id
|String
|Unique hexadecimal identifier of the user.
|true

|username
|String
|Unique name of user
|true

|email
|String
|Unique email of user.
|true

|role
|String
|Security role of user.
|true
|===

.Response Example
[%collapsible]
====
[source,http,options="nowrap"]
----
HTTP/1.1 201 Created
Content-Type: application/json; charset=utf-8
Content-Length: 92

{
	"id": "6207aedb47835c305054423c",
	"username": "maxi",
	"email": "maxi@gmail.com",
	"role": "MEMBER"
}
----
====

===== Get users
Get all available users paged. See <<_pagination, Pagination>> for details.

[horizontal]
Method:: GET
Path:: /api/v1/users
Authentication:: Yes
Pagination:: Yes
Filtering:: Yes

====== Request

.Request Example
[%collapsible]
====
[source,http,options="nowrap"]
----
GET /api/v1/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU5JU1RSQVRPUiIsImlhdCI6MTY0NTExMzQ4NiwiZXhwIjoxNjQ1MTEzNzg2LCJpc3MiOiJUd2FkZGxlIEFQSSIsInN1YiI6Im1heGkifQ.YuwEfMI8h9VHj3kou5pfVDe6tvQHKpNdNUoe0mFpCLxRTufpWxtOg0gd_chXq8ffXVov0qxyZ1ig_HwdbwGUFHZWtdL2PNUkqNkPbAfHB_N_gLmBGXBACgn1DPaFItaNKi0gE3loCgHmGemL4ONEk-si02GrsfqJQL96bwGAaB8
Accept: application/json
----
====

====== Response

.Response Fields
[cols="1,1,1,1] 
|===
|Field |Type |Description |Required

|content
|Array
|Array of found resources.
|true

|content[].id
|String
|Unique hexadecimal identifier of the user.
|true

|content[].username
|String
|Unique username of account.
|true

|content[].email
|String
|Unique email of account.
|true

|content[].role
|String
|Security role of user.
|true

|content[].blocked
|Boolean
|Blocks a user account.
|true
|===

.Response Example
[%collapsible]
====
[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Content-Length: 215

{
	"content": [
		{
	    "id": "6207aedb47835c305054423c",
	    "username": "maxi",
	    "email": "maxi@gmail.com",
	    "role": "MEMBER"
      "blocked": false
    }
	],
	"info": {
		"page": 0,
		"perPage": 25,
		"totalPages": 1,
		"totalElements": 1
	}
}
----
====

===== Get user
Get a user by its identifier.

[horizontal]
Method:: GET
Path:: /api/v1/users/:id
Authentication:: Yes

====== Request

.Path Variables
[cols="1,1,1] 
|===
|Variable |Type |Description |Required

|id
|String
|Unique identifier of user to search for.
|true
|===

.Request Example
[%collapsible]
====
[source,http,options="nowrap"]
----
GET /api/v1/users/6207aedb47835c305054423c HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU5JU1RSQVRPUiIsImlhdCI6MTY0NTExMzQ4NiwiZXhwIjoxNjQ1MTEzNzg2LCJpc3MiOiJUd2FkZGxlIEFQSSIsInN1YiI6Im1heGkifQ.YuwEfMI8h9VHj3kou5pfVDe6tvQHKpNdNUoe0mFpCLxRTufpWxtOg0gd_chXq8ffXVov0qxyZ1ig_HwdbwGUFHZWtdL2PNUkqNkPbAfHB_N_gLmBGXBACgn1DPaFItaNKi0gE3loCgHmGemL4ONEk-si02GrsfqJQL96bwGAaB8
Accept: application/json
----
====

====== Response

.Response Fields
[cols="1,1,1,1] 
|===
|Field |Type |Description |Required

|id
|String
|Unique hexadecimal identifier of the user.
|true

|username
|String
|Unique name of user
|true

|email
|String
|Unique email of user.
|true

|role
|String
|Security role of user.
|true

|blocked
|Boolean
|Blocks a user account.
|true
|===

.Response Example
[%collapsible]
====
[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Content-Length: 92

{
	"id": "6207aedb47835c305054423c",
	"username": "maxi",
	"email": "maxi@gmail.com",
	"role": "MEMBER"
}
----
====

===== Delete user
Delete a user by its identifier.

[horizontal]
Method:: DELETE
Path:: /api/v1/users/:id
Authentication:: Yes

====== Request

.Path Variables
[cols="1,1,1] 
|===
|Variable |Type |Description |Required

|id
|String
|Unique identifier of user to search for.
|true
|===

.Request Example
[%collapsible]
====
[source,http,options="nowrap"]
----
DELETE /api/v1/users/6207aedb47835c305054423c HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU5JU1RSQVRPUiIsImlhdCI6MTY0NTExMzQ4NiwiZXhwIjoxNjQ1MTEzNzg2LCJpc3MiOiJUd2FkZGxlIEFQSSIsInN1YiI6Im1heGkifQ.YuwEfMI8h9VHj3kou5pfVDe6tvQHKpNdNUoe0mFpCLxRTufpWxtOg0gd_chXq8ffXVov0qxyZ1ig_HwdbwGUFHZWtdL2PNUkqNkPbAfHB_N_gLmBGXBACgn1DPaFItaNKi0gE3loCgHmGemL4ONEk-si02GrsfqJQL96bwGAaB8
Accept: application/json
----
====

====== Response

.Response Example
[%collapsible]
====
[source,http,options="nowrap"]
----
HTTP/1.1 204 No Content
Content-Type: application/json; charset=utf-8
----
====

===== Update user
Update a user by its identifier.

[horizontal]
Method:: PATCH
Path:: /api/v1/users/:id
Authentication:: Yes

====== Request

.Path Variables
[cols="1,1,1] 
|===
|Variable |Type |Description |Required

|id
|String
|Unique identifier of user to search for.
|true
|===

.Request Fields
[cols="1,1,1] 
|===
|Variable |Type |Description |Required

|email
|String
|New email of user.
|false

|password
|String
|New password of user.
|false

|blocked
|Boolean
|Blocks a user account.
|false
|===

.Request Example
[%collapsible]
====
[source,http,options="nowrap"]
----
PATCH /api/v1/users/6207aedb47835c305054423c HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU5JU1RSQVRPUiIsImlhdCI6MTY0NTExMzQ4NiwiZXhwIjoxNjQ1MTEzNzg2LCJpc3MiOiJUd2FkZGxlIEFQSSIsInN1YiI6Im1heGkifQ.YuwEfMI8h9VHj3kou5pfVDe6tvQHKpNdNUoe0mFpCLxRTufpWxtOg0gd_chXq8ffXVov0qxyZ1ig_HwdbwGUFHZWtdL2PNUkqNkPbAfHB_N_gLmBGXBACgn1DPaFItaNKi0gE3loCgHmGemL4ONEk-si02GrsfqJQL96bwGAaB8
Accept: application/json
Content-Length: 29

{
  "email": "maxi@web.de"
}
----
====

====== Response

.Response Fields
[cols="1,1,1,1] 
|===
|Field |Type |Description |Required

|id
|String
|Unique hexadecimal identifier of the user.
|true

|username
|String
|Unique name of user
|false

|email
|String
|Unique email of user.
|true

|role
|String
|Security role of user.
|true

|blocked
|Boolean
|Blocks a user account.
|true
|===

.Response Example
[%collapsible]
====
[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Content-Length: 90

{
	"id": "6207aedb47835c305054423c",
	"username": "maxi",
	"email": "maxi@web.com",
	"role": "MEMBER"
}
----
====
